site_name: Understanding the Memetic Activation Platform
site_url: https://memetic-activation-platform.github.io/docs-understanding-map/
repo_url: https://github.com/memetic-activation-platform/docs-understanding-map
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.top
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path: docs

nav:
  - Home: index.md

  - MAP Foundations:
      - A New MAP Overview: overview.md
      - Collective Governance Scaffolds: collective-governance.md
      - MAP Promises: promises.md
      - Promise Weaves: promise-weaves.md
      - Vital Capital Flows: vital-capital-flows.md
      - MAP Security Model: security-model.md
      - Greet the DAHN: DAHN.md
      - Promise Agreements: promise-agreements.md
      - Uniform API (Dances): uniform-api.md
      - Ethical AI & RAG: ethical-ai-rag.md
      - Agreements, Agent Spaces and LifeCodes: agreements-spec.md
      - Glossary: glossary.md
