site_name: Understanding the Memetic Activation Platform
site_url: https://memetic-activation-platform.github.io/docs-understanding-map/
repo_url: https://github.com/memetic-activation-platform/docs-understanding-map
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - search.highlight
    - navigation.top
    - navigation.footer
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - assets/glossary-hover.js

extra:
  glossary_json: assets/glossary.json

extra_css:
  - overrides/styles.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path: docs

nav:
  - Home: index.md

  - Understanding the MAP:
    - Prologue: understanding-the-map/prologue.md
    - Ecosystems Overview: understanding-the-map/ecosystem-intro.md
    - Overview: understanding-the-map/overview.md
    - Principles: understanding-the-map/principles.md

    # Personal & Agent Foundations
    - Agents and Spaces: understanding-the-map/agents-and-spaces.md
    - From Data Grove to Exosphere: understanding-the-map/private-data-grove.md
    - MAP Promises: understanding-the-map/promises.md
    - Offers and Agreements: understanding-the-map/offers-and-agreements.md
    - Promise Weaver Protocol: understanding-the-map/promise-weaver.md

    # Value Flows and Governance
    - Vital Capital Flows: understanding-the-map/vital-capital-flows.md
    - Collective Governance Scaffolds: understanding-the-map/collective-governance.md

    # Choreography, Protocols & Platform Intelligence
    - Choreographing Dance Flows: understanding-the-map/choreographer.md
    - Uniform API (Dances): understanding-the-map/uniform-api.md

    # Security, AI, and Experience
    - MAP Security Model: understanding-the-map/security-model.md
    - Greet the DAHN: understanding-the-map/DAHN.md
    - Ethical AI Knowledge Assistants: understanding-the-map/ethical-ai-rag.md

    # Reference
    - Appendices:
      - Glossary: understanding-the-map/appendices/glossary.md
      - Formal Definitions: understanding-the-map/appendices/formal-definitions.md
      - Why Vital Capitals?: understanding-the-map/appendices/vital-capital-lineage.md

  - Journeys:
    - Introduction: journeys/journeys-index.md
    - Personal Journaling: journeys/personal-journal.md
    - Web-Conference: journeys/web-conference.md
    - Case Study -- Sharing an AirBnB: journeys/sharing-lodging.md
    - Commitment Pools Example: journeys/commitment-pools.md
    - Regen Choice: journeys/regen-choice.md
    - Commoning Journey:
        - Prologue: journeys/commoning-journey/0.2-prologue.md
        - MAP Orientation: journeys/commoning-journey/0.5-map-orientation.md
        - Commoning Lifecycle: journeys/commoning-journey/0.3-commoning-lifecycle.md
        - Inception: journeys/commoning-journey/1-inception.md
        - Formation: journeys/commoning-journey/2-formation.md
        - Stewardship: journeys/commoning-journey/3-stewardship.md
        - Regeneration: journeys/commoning-journey/4-regeneration.md
        - Completion: journeys/commoning-journey/5-completion.md
        - Commoning on MAP: journeys/commoning-journey/commoning-on-map.md